[tool.poetry]
name = "whats"
version = "0.1.0"
description = ""
authors = ["Saimon"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
selenium = "^4.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
